services:
  DisplayHub-mongodb:
    image: mongo
    volumes:
      - DisplayHub_mongodb_data:/data/db
    container_name: displayhub-mongodb
    ports:
      - "27018:${MONGODB_PORT}"

  DisplayHub-client:
    build:
      context: ./client
      dockerfile: ${DOCKERFILE_CLIENT:-Dockerfile}
    container_name: displayhub-client
    image: displayhub-client
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.DisplayHub-client.rule=Host(`${VITE_CLIENT_URL}`)"
      - "traefik.http.routers.DisplayHub-client.entrypoints=websecure"
      - "traefik.http.routers.DisplayHub-client.tls.certresolver=myresolver"
    environment:
      VITE_CLIENT_URL: ${VITE_CLIENT_URL}
      VITE_SERVER_URL: ${VITE_SERVER_URL}
      VITE_ADMIN_URL: ${VITE_ADMIN_URL}
      VITE_COOKIE_DOMAIN: ${VITE_COOKIE_DOMAIN}
      VITE_CLIENT_PORT: ${VITE_CLIENT_PORT}
    volumes:
      - ./client:/app
      - .env:/app/.env
      - /app/node_modules
    ports:
      - "${VITE_CLIENT_PORT}:${VITE_CLIENT_PORT}"

  DisplayHub-admin:
    build:
      context: ./admin
      dockerfile: ${DOCKERFILE_CLIENT:-Dockerfile.dev}
    container_name: displayhub-admin
    image: displayhub-admin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.DisplayHub-admin.rule=Host(`${VITE_ADMIN_URL}`)"
      - "traefik.http.routers.DisplayHub-admin.entrypoints=websecure"
      - "traefik.http.routers.DisplayHub-admin.tls.certresolver=myresolver"
    environment:
      VITE_CLIENT_URL: ${VITE_CLIENT_URL}
      VITE_SERVER_URL: ${VITE_SERVER_URL}
      VITE_ADMIN_URL: ${VITE_ADMIN_URL}
      VITE_COOKIE_DOMAIN: ${VITE_COOKIE_DOMAIN}
      VITE_ADMIN_PORT: ${VITE_ADMIN_PORT}
    volumes:
      - ./admin:/app
      - .env:/app/.env
      - /app/node_modules
    ports:
      - "${VITE_ADMIN_PORT}:${VITE_ADMIN_PORT}"


  DisplayHub-server:
    build:
      context: ./server
      dockerfile: ${DOCKERFILE_CLIENT:-Dockerfile.dev}
    image: displayhub-server
    container_name: displayhub-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.DisplayHub-server.rule=Host(`${VITE_SERVER_URL}`)"
      - "traefik.http.services.DisplayHub-server.loadbalancer.server.port=${VITE_SERVER_PORT}"
      - "traefik.http.routers.DisplayHub-server.entrypoints=websecure"
      - "traefik.http.routers.DisplayHub-server.tls.certresolver=myresolver"
    volumes:
      - ./server:/app
      - ./server/uploads:/app/uploads
      - ./server/public:/app/public
      - /app/node_modules
      - .env:/app/.env
    env_file: .env
    ports:
      - "${VITE_SERVER_PORT}:${VITE_SERVER_PORT}"

  DisplayHub-vitrine:
    build:
      context: ./vitrine
      dockerfile: ${DOCKERFILE_CLIENT:-Dockerfile.dev}
    image: displayhub-vitrine
    container_name: displayhub-vitrine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.DisplayHub-vitrine.rule=Host(`${VITE_VITRINE_URL}`)"
      - "traefik.http.routers.DisplayHub-vitrine.entrypoints=websecure"
      - "traefik.http.routers.DisplayHub-vitrine.tls.certresolver=myresolver"
    env_file: .env
    volumes:
      - ./vitrine:/app
      - .env:/app/.env
      - /app/node_modules
    ports:
      - "${VITE_VITRINE_PORT}:3000"

volumes:
  DisplayHub_mongodb_data:
    driver: local