services:
  DisplayHub-mongodb:
    image: mongo
    volumes:
      - DisplayHub_mongodb_data:/data/db

  DisplayHub-client:
    build:
      context: ./client
      args:
        VITE_INSTANCE_URL: "https://client.displayhub.fr"
        VITE_SERVER_URL: "https://api.displayhub.fr"
    image: displayhub-client
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.DisplayHub-client.rule=Host(`client.displayhub.fr`)"
      - "traefik.http.routers.DisplayHub-client.entrypoints=websecure"
      - "traefik.http.routers.DisplayHub-client.tls.certresolver=myresolver"

  DisplayHub-admin:
    build:
      context: ./admin
      args:
        VITE_INSTANCE_URL: "https://admin.displayhub.fr"
        VITE_SERVER_URL: "https://api.displayhub.fr"
    image: displayhub-admin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.DisplayHub-admin.rule=Host(`admin.displayhub.fr`)"
      - "traefik.http.routers.DisplayHub-admin.entrypoints=websecure"
      - "traefik.http.routers.DisplayHub-admin.tls.certresolver=myresolver"


  DisplayHub-server:
    build:
      context: ./server
    env_file: ./server/.env
    environment:
      DB_URI: mongodb://DisplayHub-mongodb:27017/DisplayHub
    image: displayhub-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.DisplayHub-server.rule=Host(`api.displayhub.fr`)"
      - "traefik.http.services.DisplayHub-server.loadbalancer.server.port=3001"
      - "traefik.http.routers.DisplayHub-server.entrypoints=websecure"
      - "traefik.http.routers.DisplayHub-server.tls.certresolver=myresolver"
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/public:/app/public

  DisplayHub-vitrine:
    build:
      context: ./vitrine
    image: displayhub-vitrine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.DisplayHub-vitrine.rule=Host(`displayhub.fr`)"
      - "traefik.http.routers.DisplayHub-vitrine.entrypoints=websecure"
      - "traefik.http.routers.DisplayHub-vitrine.tls.certresolver=myresolver"

volumes:
  DisplayHub_mongodb_data:
    driver: local